"""add post.body_html

Revision ID: 4e9c21ac29cd
Revises: cb4f610ea26b
Create Date: 2024-06-25 23:47:27.078070

"""

# revision identifiers, used by Alembic.
revision = '4e9c21ac29cd'
down_revision = 'cb4f610ea26b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
