"""add post.body_html

Revision ID: 62493093fe3d
Revises: 4e9c21ac29cd
Create Date: 2024-06-25 23:47:45.079572

"""

# revision identifiers, used by Alembic.
revision = '62493093fe3d'
down_revision = '4e9c21ac29cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
