"""add comfirm column

Revision ID: 9a91210e871b
Revises: 0ebd812be183
Create Date: 2024-06-10 10:51:13.690358

"""

# revision identifiers, used by Alembic.
revision = '9a91210e871b'
down_revision = '0ebd812be183'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
